### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mario-pandzic** [roshandarji/synthwaveBLACK#2]
Unable to install the theme. The URL seems to be broken:

trying URL 'https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/synthwaveBLACK.rstheme'
Error in utils::download.file(themePath, path) : 
  cannot open URL 'https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/synthwaveBLACK.rstheme'
In addition: Warning message:
In utils::download.file(themePath, path) :
  cannot open URL 'https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/synthwaveBLACK.rstheme': HTTP status was '404 Not Found'

**Comment by roshandarji** [comment]
Sorry I'm dumb and put in the wrong link in the README. The proper URL should be https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/SynthwaveBlack.rstheme. 

If you run the following, it should work now. 
`rstudioapi::addTheme("https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/SynthwaveBlack.rstheme", TRUE, TRUE, FALSE)`
